### PR TITLE
Search whole class hierarchy when enabling/disabling features

### PR DESCRIPTION
**Pull request by vmuzikar**

### CODE REVIEW

**Review by ssilvert — COMMENTED** [review]
@vmuzikar  I'm fine with this.  Just two questions.

1. I take it that an annotation in the subclass wins over the superclass?  In other words, if two or more classes in the hierarchy both toggle the same feature, the one closest to the leaf node wins?

2. Have you run the admin and account console tests with this change?  What were the results?  Have you run any other test suites with this change?  Results?

**Comment by vmuzikar** [comment]
@ssilvert
1. Yes, exactly.
2. Not yet. Triggered the pipelines now:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/2029/
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1628/
I don't expect any failures caused by this. Even though it might not seem so, it's a relatively small change which doesn't modify the current behaviour in most cases (before now, we didn't need to "combine" the enable/disable annotations, i.e. we had only one annotation in given class hierarchy).

**Comment by ssilvert** [comment]
> 2. Not yet. Triggered the pipelines now:
>    https://keycloak-jenkins.com/job/universal-test-pipeline-server/2029/
>    https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1628/
>    I don't expect any failures caused by this. Even though it might not seem so, it's a relatively small change which doesn't modify the current behaviour in most cases (before now, we didn't need to "combine" the enable/disable annotations, i.e. we had only one annotation in given class hierarchy).

Let me know if the tests look good.  If so, I'll merge.

**Comment by vmuzikar** [comment]
New test results:
https://keycloak-jenkins.com/job/universal-test-pipeline-server/2033/
https://keycloak-jenkins.com/job/universal-test-pipeline-adapters/1631/

The tests look ok, my changes didn't break anything. But we still need to resolve the issues mentioned in the main PR (which are not caused by this).

@ssilvert Feel free to merge this. :)

**Pull request merged**
